INSERT INTO USER(USER_I, USER_NAME, PASSWRD, NICK_NAME, ACTIVATED)  VALUES (1,'admin', '12341234')

INSERT INTO AUTHORITY(AUTHORITY_NAME) VALUES('ROLE_USER');
INSERT INTO AUTHORITY(AUTHORITY_NAME) VALUES('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY(USER_ID,AUTHORITY_NAME) VALUES(1,'ROLE_USER');
INSERT INTO USER_AUTHORITY(USER_ID,AUTHORITY_NAME) VALUES(1,'ROLE_ADMIN');